services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.app.wsgi:application"
    envVars:      
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 0